/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductListingsRouteImport } from './routes/$productListings'
import { Route as IndexRouteImport } from './routes/index'

const ProductListingsRoute = ProductListingsRouteImport.update({
  id: '/$productListings',
  path: '/$productListings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$productListings': typeof ProductListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$productListings': typeof ProductListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$productListings': typeof ProductListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$productListings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$productListings'
  id: '__root__' | '/' | '/$productListings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductListingsRoute: typeof ProductListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$productListings': {
      id: '/$productListings'
      path: '/$productListings'
      fullPath: '/$productListings'
      preLoaderRoute: typeof ProductListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductListingsRoute: ProductListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
